manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic/
    - name: halfdane
      url-base: https://github.com/halfdane/
    - name: johanson
      url-base: https://github.com/petejohanson
    - name: miryoku
      url-base: https://github.com/manna-harbour/
  projects:
    - name: zmk
      remote: halfdane
      revision: rp2040zero
      import: app/west.yml
    # - name: zmk
    #   remote: johanson
    #   revision: split/wired-split-first-pass
    #   import: app/west.yml
    - name: miryoku_zmk
      remote: miryoku
      revision: master
  self: 
    path: config
