manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: miketronic
      url-base: https://github.com/miketronic/
  projects:
    - name: zmk
      remote: miketronic
      revision: rp2040zero
      import: app/west.yml
  self: 
    path: config
