points:
  zones:
    matrix:
      columns:
        pinky.rotate: 10
        ring.rotate: -10
        ring.stagger: 0.66U
        middle.stagger: 0.25U
        index.stagger: -0.25U
        inner.stagger: -0.15U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [-0.3U, -1.1U]
        rotate: -10
      columns:
        tucky:
          key.name: thumb_tucky
        middle:
          key.name: thumb_middle
          origin: [-0.5U, -0.3U]
        reachy:
          key.name: thumb_reachy
          origin: [-0.5U, -0.3U]
outlines:
  exports:
    _raw:
      - type: keys
        side: left
        size: [ 28, 28 ]
        corner: 2
    _clip_thumb_hole:
      - type: rectangle
        size: [40, 30]
        anchor:
          shift: [0, -11]
          rotate: -10
    _clip_pinkie_hole:
      - type: rectangle
        size: [40, 30]
        anchor:
          shift: [-10, 19.8]
          rotate: 10
    _clip_top_stagger:
      - type: rectangle
        size: [104, 20.5]
        corner: 2
        anchor:
          shift: [2, 51.7]
    plate: [
      +_raw,
      +_clip_thumb_hole,
      +_clip_pinkie_hole,
      +_clip_top_stagger
    ]
    _switch_holes:
      - type: keys
        side: left
        size: [ 14,14 ]
    switch_plate:
      - +plate
      - -_switch_holes

      