units:
  thumb_rotation: -10
  pinky_rotation: 10

points:
  zones:
    matrix:
      columns:
        pinky.rotate: pinky_rotation
        ring.rotate: -pinky_rotation
        ring.stagger: 0.66U
        middle.stagger: 0.25U
        index.stagger: -0.25U
        inner.stagger: -0.15U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [-0.3U, -1U]
        rotate: thumb_rotation
      columns:
        tucky:
          key.name: thumb_tucky
        middle:
          key.name: thumb_middle
          origin: [-0.5U, -0.3U]
        reachy:
          key.name: thumb_reachy
          origin: [-0.5U, -0.3U]
  mirror:
    distance: 3U
    ref: thumb_reachy
outlines:
  exports:
    _raw_plate:
      - type: keys
        side: left
        size: [ 24, 24 ]
        corner: 2
    _clip_pinkie_hole_top:
      - type: rectangle
        size: [50, 24]
        anchor:
          ref: matrix_pinky_top
          shift: [-12, 0]
    _clip_pinkie_hole_bottom:
      - type: rectangle
        size: [20, 10]
        anchor:
          ref: matrix_pinky_bottom
          shift: [0, -12]
    _clip_thumb_hole:
      - type: rectangle
        size: [40, 30]
        anchor:
          ref: thumb_tucky
          shift: [-40, -12]
    _clip_top_stagger:
      - type: rectangle
        size: [108, 20]
        corner: 2
        anchor:
          ref: matrix_ring_top
          shift: [-39, 2]
    _thumb_screw:
      - type: rectangle
        size: [25, 30]
        corner: 10
        anchor:
          ref: thumb_reachy
          shift: [-13, -4]
    _thumb_screw_hole:
      - type: circle
        radius: 2.5
        anchor:
          ref: thumb_reachy
          shift: [2, 17]
    _pinkie_low_screw_hole:
      - type: circle
        radius: 2.5
        anchor:
          ref: matrix_pinky_bottom
          shift: [20, -5]
    _pinkie_top_screw_hole:
      - type: circle
        radius: 2.5
        anchor:
          ref: matrix_pinky_top
          shift: [-3, 32]
    _inner_top_screw_hole:
      - type: circle
        radius: 2.5
        anchor:
          ref: matrix_inner_top
          shift: [3, 16]
    _chip:
      second_phase:
        operation: add
        type: rectangle
        size: [9, 9]
        anchor:
          ref: matrix_ring_top
          shift: [-22.5, 14]
      third_phase:
        operation: add
        type: rectangle
        size: [3.6, 4.3]
        anchor:
          ref: matrix_ring_top
          shift: [-24.3, 0]
      fourth_phase:
        operation: add
        type: rectangle
        size: [3.6, 4.3]
        anchor:
          ref: matrix_ring_top
          shift: [-15.3, 0]
    plate: [
      +_raw_plate,
      +_clip_thumb_hole,
      +_clip_top_stagger,
      +_clip_pinkie_hole_top,
      +_clip_pinkie_hole_bottom,
      +_thumb_screw,
      -_thumb_screw_hole,
      -_pinkie_low_screw_hole,
      -_inner_top_screw_hole,
      -_pinkie_top_screw_hole,
      -_chip
    ]
    _switch_holes:
      - type: keys
        side: both
        size: [ 14,14 ]
    switch_plate:
      - +plate
      - -_switch_holes


