##########################################
###
###     Given conditions:
###     - Each layer is 0.5mm high (thickness of the veneer I bought)
###     - Height of USB-hole: 3mm (6 layers)
###     - Height/width of halves'/mouse connectors holes: 5mm/10mm
###     - M2-Screws and inlets
###     - Kailh choc switches
###     - Keycaps are 17mmx16mm
###     - Keycaps are NOT 18mmx18mm as usual!!
###     - Rubber bumpers are 4mm radius
###     - Magnets have 5mm radius and almost 2mm thickness (4 layers)
###     - Cirque Trackpad 40 - 39mm overlay / 41mm overlay lip
###       Case needs a bit space around, so maybe 43mm in total?
###       => 19.5mm overlay hole radius
###       => 20.5mm overlay lip hole radius
###       => 21.5mm outer casing radius
###
##########################################

units:
  # MY KEYCAPS: 17.5mmx16.5mm
  # cx and cy:  18.0mmx17.0mm for kailh choc
  kx: cx
  ky: cy
  # with padding
  px: kx + 1
  py: ky + 1

  # size of holes in switch plate
  sh: 14

  rp2040_body_width: 23.5
  rp2040_body_height: 18

  thumb_rotation: -8
  pinky_rotation: 8

  m2_screw_radius: 1
  m2_head_radius: 1.8
  m2_inlet_radius: 1.5
  m2_outer_distance: 2.5

  rubber_bumper_radius: 4

  magnet_radius: 5.1

  symbols_radius_recess: 4
  symbols_radius_piece: 4.05

  base_width: 105
  base_height: 82

  middle_stagger: 0.7ky
  
  keyboard_tl_x: 0.5*base_width - rp2040_body_width + m2_outer_distance
  keyboard_tl_y: 0.5*base_height - middle_stagger

  connector_width: 10
  connector_length: 6
  
  cirque_case_radius: 21.5

points:
  zones:      
    symbol.anchor:
      shift: [(rp2040_body_width + m2_outer_distance)/2, -base_height/2-middle_stagger+m2_outer_distance]
    keyboard_tl.anchor:
      shift: [keyboard_tl_x, keyboard_tl_y]

    matrix:
      key:
        padding: 1ky
        spread: 1kx

      columns:
        pinky.key.splay: pinky_rotation
        ring.key.splay: -pinky_rotation
        ring.key.stagger: middle_stagger
        middle.key.stagger: 0.5ky
        index.key.stagger: -0.25ky
        inner.key.stagger: -0.25ky
      rows:
        bottom:
        home: 
        top: 
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-6.5, -18]
        rotate: thumb_rotation
      columns:

        middle:
          key.name: thumb_middle
          key.origin: [-0.5U, -0.3U]
        reachy:
          key.name: thumb_reachy
          key.origin: [-0.5U, -0.3U]

outlines:
  _base:
    - what: rectangle
      size: [base_width, base_height]
      corner: 1
      where:
        ref: keyboard_tl
  
  ### holes for magnets to hold the two sides together when transporting
  _magnet_hole_top_left:
    - what: circle
      radius: magnet_radius
      where:
        shift: [-base_width/2+magnet_radius+(m2_outer_distance*2.5)+rp2040_body_width, base_height/2-magnet_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _magnet_hole_top_right:
    - what: circle
      radius: magnet_radius
      where:
        shift: [base_width/2-magnet_radius-(m2_outer_distance/2), base_height/2-magnet_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _magnet_hole_bottom_left:
    - what: circle
      radius: magnet_radius
      where:
        shift: [-base_width/2+magnet_radius+(m2_outer_distance/2), -base_height/2+magnet_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _magnet_holes: [
    _magnet_hole_top_left,
    _magnet_hole_top_right,
    _magnet_hole_bottom_left,
  ]

  ### holes&inlets for m2 screws 
  _screw_tl:
    - what: circle
      radius: m2_screw_radius
      where: 
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_tl:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_tl:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_tr:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_tr:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_tr:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_thumb_top:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), -base_height*0.3]
        ref: keyboard_tl
  _head_thumb_top:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), -base_height*0.3]
        ref: keyboard_tl
  _inlet_thumb_top:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), -base_height*0.3]
        ref: keyboard_tl
  _screw_thumb_bottom:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [base_width/3+m2_head_radius+4, -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_thumb_bottom:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [base_width/3+m2_head_radius+4, -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_thumb_bottom:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [base_width/3+m2_head_radius+4, -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_bl:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_bl:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_bl:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_holes: [
    _screw_tl,
    _screw_tr,
    _screw_thumb_top,
    _screw_thumb_bottom,
    _screw_bl,
  ]
  _screw_heads: [
    _head_tl,
    _head_tr,
    _head_thumb_top,
    _head_thumb_bottom,
    _head_bl,
  ]
  _inlet_holes: [
    _inlet_tl,
    _inlet_tr,
    _inlet_thumb_top,
    _inlet_thumb_bottom,
    _inlet_bl,
  ]
        
  ### rp2040 needs a place
  _rp2040_body:
    - what: rectangle
      size: [rp2040_body_width, rp2040_body_height+2]
      where:
        ref: keyboard_tl
        shift: [-base_width/2+rp2040_body_width/2+m2_outer_distance*2/3, base_height/2-rp2040_body_height+3]
    - what: rectangle
      size: [1, 13]
      where:
        ref: keyboard_tl
        shift: [-base_width/2+rp2040_body_width+2.1, base_height/2-rp2040_body_height+3]

  _rp2040_usb:
    - what: rectangle
      size: [8, 9.5]
      where:
        ref: keyboard_tl
        shift: [-base_width/2, base_height/2-rp2040_body_height+3]
  _rp2040: [
    _rp2040_body,
    _rp2040_usb
  ]

  ### connectors to touchpad or between halves
  _connector_hole_tt:
    - what: rectangle
      size: [connector_width, connector_length]
      where:
        ref: keyboard_tl
        shift: [base_width/2-px*2/3, base_height/2-connector_length/2+0.001]
    - what: rectangle
      size: [connector_width-1, connector_length+5]
      where:
        ref: keyboard_tl
        shift: [base_width/2-px*2/3, base_height/2-connector_length*2+1]
  _connector_hole_bt:
    - what: rectangle
      size: [connector_width, connector_length]
      where:
        ref: keyboard_tl
        shift: [13, -base_height/2+connector_length/2-0.001]
    - what: rectangle
      size: [connector_width-1, connector_length+10]
      where:
        ref: keyboard_tl
        shift: [13, -base_height/2+connector_length+(connector_length+10)/2-0.001]
  _connector_holes: [
    _connector_hole_bt,
    _connector_hole_tt
  ]
  
  ### symbol
  _symbol_recess:
    - what: circle
      radius: symbols_radius_recess
      where:
        shift: [0, 0]
    - what: circle
      radius: symbols_radius_recess
      where:
        shift: [12, 0]
    - what: circle
      radius: symbols_radius_recess
      where:
        shift: [6, 10.3]
    - what: polygon
      operation: subtract
      points:
        - shift: [0,0]
        - shift: [12, 0]
        - shift: [-6, 10.3]

  symbol_pieces:
    - what: circle # left
      radius: symbols_radius_piece
      where:
        shift: [0, 0]
    - what: circle # right
      radius: symbols_radius_piece+0.05
      where:
        shift: [12, 0]
    - what: circle # top
      radius: symbols_radius_piece+0.1
      where:
        shift: [6, 10.3]
    - what: polygon # triangle
      operation: subtract
      points:
        - shift: [0,0]
        - shift: [12, 0]
        - shift: [-6, 10.3]

  
  _touchpad_case:
    - what: circle
      radius: cirque_case_radius
      where:
        ref: keyboard_tl
        shift: [0, -base_height/2-5]
  _magnet_touchpad:
    - what: circle
      radius: magnet_radius
      where:
        ref: keyboard_tl
        shift: [0, -base_height/2+cirque_case_radius/2-1]

  ### parts that are used on different layers
  _rubber_bumper_tl:
    - what: circle
      radius: rubber_bumper_radius
      where: 
        shift: [-base_width/2+m2_head_radius+m2_outer_distance+rubber_bumper_radius, base_height/2-m2_head_radius-m2_outer_distance-rubber_bumper_radius]
        ref: keyboard_tl
  _rubber_bumper_tr:
    - what: circle
      radius: rubber_bumper_radius
      where:
        shift: [base_width/2-m2_head_radius-m2_outer_distance-rubber_bumper_radius, base_height/2-m2_head_radius-m2_outer_distance-rubber_bumper_radius]
        ref: keyboard_tl
  _rubber_bumper_bl:
    - what: circle
      radius: rubber_bumper_radius
      where:
        shift: [-base_width/2+m2_head_radius+m2_outer_distance+rubber_bumper_radius, -base_height/2+m2_head_radius+m2_outer_distance+rubber_bumper_radius]
        ref: keyboard_tl
  _rubber_bumper_br:
    - what: circle
      radius: rubber_bumper_radius
      where:
        shift: [base_width/2, -base_height/2+rubber_bumper_radius+1.5]
        ref: keyboard_tl
  _rubber_bumpers: [
    _rubber_bumper_tl,
    _rubber_bumper_tr,
    _rubber_bumper_bl,
    _rubber_bumper_br
  ]

  ### switch plate
  _thumbs:
    - what: rectangle
      size: [3U, 1U]
      corner: 1
      where:
        ref: thumb_reachy
        shift: [-1U, 0]
  _key_holes:
    - what: rectangle
      where: /^matrix_.*|^thumb_.*/
      size: sh
  _key_frame:
    - what: rectangle
      where: 
        ref: matrix_middle_top
      bound: true
      size: 14
      expand: 8

  _raw_plate:
    - what: outline
      name: _base
    - what: outline
      name: _key_frame
      operation: add
      where:
        shift: [0, 1]
  _with_fillets:
    - what: outline
      name: _raw_plate
      fillet: 4

  ### frame around keycaps on top of switchplate
  _switch_caps:
    - what: rectangle
      # operation: stack
      where: /^matrix_.*/
      size: [px, py]
    - what: rectangle
      # operation: stack
      where: /^thumb_.*/
      size: [px, py+10]
  

  _bottom_hollow:
    - what: rectangle
      fillet: 2
      where: /^matrix_.*/
      size: [kx, ky]
    - what: rectangle
      fillet: 2
      where: /^thumb_.*/
      size: sh
    - what: rectangle
      size: [5, 10]
      where:
        ref: keyboard_tl
        shift: [-25, 22]
    - what: rectangle
      size: [8, 5]
      where:
        ref: thumb_reachy
        shift: [-10, 3]
    - what: rectangle
      size: [5, 8]
      where:
        ref: thumb_reachy
        shift: [-18, 9]
      

##########################################
###
###     The actual Layers ordered from bottom to top:
###     - 3 layers of bottom plate that can be screwed on and off
###     - 10 layers of bottom hollow that holds wiring etc
###     - 3 layers of switch plate
###     - 15 layers of top cap that hold rp2040, magnets and inlay
###
###   Gluing order:
###     - the three switch plates
###     - the bottom plates
###     - bottom hollow to the switch plate
###     - glue the two topmost layers
###     - glue the top cap to the switch plate
###     - glue two topmost layers to the rest
###
###   Gluing stabilizer (use test cuts):
###     - 4x a switch plate or layer_02 - everything but top cap
###     - 2x layer_30 - for the top cap stuff
###
###   Test cut with cheap wood
###     - layer_14, layer_15, layer_16 (all three switch plate layers)
###     - layer_02 (second bottom layer - without voronoi)
###     - layer_31 (top cap with symbol recess)
###     - symbol_pieces
###
##########################################

  ## bottom plate consists of three layers: 
  ## 01: the voronoi pattern with big holes for the screw heads and the rubber bumpers
  ## 02: a blank outline (using a different wood) - maybe with space invaders inlay?
  ## 03: the voronoi pattern again so that keys can be closer to the bottom
  ## Layer 01 has larger holes to accomodate the screw heads, the other layers'
  ##   holes are just large enough to the screws can fit through

  _key_pattern:
    - what: circle
      where: false
      # where: /^matrix_.*|^thumb_.*/
      radius: 01
  layer_01: [
    _with_fillets,
    +_thumbs,
    -_key_pattern,
    -_screw_heads,
    -_rubber_bumpers
  ]
  layer_02: [
    _with_fillets,
    +_thumbs,
    -_screw_holes
  ]
  layer_03: [
    _with_fillets,
    +_thumbs,
    -_key_pattern,
    -_screw_holes
  ]

  ## body below the keyplate: 
  ##  to clear the lower part of the keys, it needs to be at least 5mm which is the same
  ##  height as the halves'/mouse connectors.
  ## So that's 10 layers in total
  ##  Bottommost layer doesn't have holes to increase stability. 
  ##  There's a connector hole in the first switch plate layer instead.
  ##
  ## 04: bottom hollow without connector holes
  ## 05-13: bottom hollow 
  ##    - with connector holes (==9 Layers - missing space is cleared by the first switch plate layer)
  ##    - with magnet holes -> double up the magnets for more holding power


  layer_04: [
    _with_fillets,
    +_thumbs,
    -_bottom_hollow,
    -_rp2040_body,
    -_screw_holes,
  ]

  layer_05_to_13: [
    _with_fillets,
    +_thumbs,
    -_bottom_hollow,
    -_rp2040_body,
    -_inlet_holes,
    -_connector_holes,
    -_magnet_touchpad
  ]

  ## switch plate consists of three layers - goal is a total of 1.5mm for the 
  ##    switch plate, and each layer is around 0.5-0.6mm 
  ##    First layer has space for connectors:
  ## 14: switch plate with holes for halves'/mouse connectors
  ## 15: switch plate
  ## 16: switch plate
  
  layer_14: [
    _with_fillets,
    +_thumbs,
    -_key_holes,
    -_rp2040_body,
    -_inlet_holes,
    -_connector_holes,
    -_magnet_touchpad
  ]
  layer_15: [
    _with_fillets,
    +_thumbs,
    -_key_holes,
    -_rp2040_body,
    -_inlet_holes
  ]
  layer_16: [
    _with_fillets,
    +_thumbs,
    -_key_holes,
    -_rp2040_body,
    -_inlet_holes
  ]

  ## body above the keyplate: 
  ##    - to clear the keycaps (7.5 mm above switch plate), 15 layers are needed in total:
  ##    - 6 layers with space for the rp2040, usb holes holes for magnets
  ##    - 3 layers with just space for the rp2040 and holes for magnets
  ##    - 4 layers with holes for magnets
  ##    - 1 layer to cover the magnets have something to glue the inlay to
  ##    - 1 layer holds the inlay
  ## That allows to triple up the magnets for superior holding power
  ## 17-22: top frame with usb hole and magnet holes
  ## 23-25: top frame with magnet holes
  ## 26-29: top frame with magnet holes
  ## 30: top layer without any holes
  ## 31: top layer with inlay
  layer_17_to_22: [
    _with_fillets,
    -_rp2040,
    -_switch_caps,
    -_touchpad_case,
    -_magnet_holes
  ]

  layer_23_to_25: [
    _with_fillets,
    -_rp2040_body,
    -_switch_caps,
    -_touchpad_case,
    -_magnet_holes
  ]

  layer_26_to_29: [
    _with_fillets,
    -_rp2040_body,
    -_switch_caps,
    -_magnet_holes,
    -_touchpad_case
  ]

  layer_30:
    - what: outline
      name: _with_fillets
    - what: outline
      name: _switch_caps
      operation: subtract
    - what: outline
      name: _touchpad_case
      operation: subtract

  layer_31:
    - what: outline
      name: _with_fillets
    - what: outline
      name: _switch_caps
      operation: subtract
    - what: outline
      name: _symbol_recess
      operation: subtract
      origin: symbol
    - what: outline
      name: _touchpad_case
      operation: subtract
    

