units:
  thumb_rotation: -8
  pinky_rotation: 8

  keyboard_tl_x: 35
  keyboard_tl_y: 30
  base_width: 108
  base_height: 87

  rp2040_body_width: 23.5
  rp2040_body_height: 18

  m2_screw_radius: 1
  m2_head_radius: 1.8
  m2_inlet_radius: 1.5
  m2_outer_distance: 2.5

  magnet_radius: 4.1

  symbols_radius: 4
  

points:
  zones:
    symbol.anchor:
      shift: [12, -55]
    keyboard_tl.anchor:
      shift: [keyboard_tl_x, keyboard_tl_y]

    matrix:
      columns:
        pinky.key.splay: pinky_rotation
        ring.key.splay: -pinky_rotation
        ring.key.stagger: 0.5U
        middle.key.stagger: 0.5U
        index.key.stagger: -0.25U
        inner.key.stagger: -0.15U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-6.5, -18]
        rotate: thumb_rotation
      columns:

        middle:
          key.name: thumb_middle
          key.origin: [-0.5U, -0.3U]
        reachy:
          key.name: thumb_reachy
          key.origin: [-0.5U, -0.3U]

outlines:
  _base:
    - what: rectangle
      size: [base_width, base_height]
      corner: 1
      where:
        ref: keyboard_tl
  
  ### holes for magnets to hold the two sides together when transporting
  _magnet_hole_top_left:
    - what: circle
      radius: magnet_radius
      where:
        shift: [-base_width/2+magnet_radius+(m2_outer_distance*2.5)+rp2040_body_width, base_height/2-magnet_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _magnet_hole_top_right:
    - what: circle
      radius: magnet_radius
      where:
        shift: [base_width/2-magnet_radius-(m2_outer_distance/2), base_height/2-magnet_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _magnet_hole_bottom_left:
    - what: circle
      radius: magnet_radius
      where:
        shift: [-base_width/2+magnet_radius+(m2_outer_distance/2), -base_height/2+magnet_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _magnet_holes: [
    _magnet_hole_top_left,
    _magnet_hole_top_right,
    _magnet_hole_bottom_left,
  ]

  ### holes&inlets for m2 screws 
  _screw_tl:
    - what: circle
      radius: m2_screw_radius
      where: 
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_tl:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_tl:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_tr:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_tr:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_tr:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), base_height/2-m2_head_radius-(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_thumb_top:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), -base_height*0.3]
        ref: keyboard_tl
  _head_thumb_top:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), -base_height*0.3]
        ref: keyboard_tl
  _inlet_thumb_top:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [base_width/2-m2_head_radius-(m2_outer_distance/2), -base_height*0.3]
        ref: keyboard_tl
  _screw_thumb_bottom:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [base_width/3+m2_head_radius+4, -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_thumb_bottom:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [base_width/3+m2_head_radius+4, -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_thumb_bottom:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [base_width/3+m2_head_radius+4, -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_bl:
    - what: circle
      radius: m2_screw_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _head_bl:
    - what: circle
      radius: m2_head_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _inlet_bl:
    - what: circle
      radius: m2_inlet_radius
      where:
        shift: [-base_width/2+m2_head_radius+(m2_outer_distance/2), -base_height/2+m2_head_radius+(m2_outer_distance/2)]
        ref: keyboard_tl
  _screw_holes: [
    _screw_tl,
    _screw_tr,
    _screw_thumb_top,
    _screw_thumb_bottom,
    _screw_bl,
  ]
  _screw_heads: [
    _head_tl,
    _head_tr,
    _head_thumb_top,
    _head_thumb_bottom,
    _head_bl,
  ]
  _inlet_holes: [
    _inlet_tl,
    _inlet_tr,
    _inlet_thumb_top,
    _inlet_thumb_bottom,
    _inlet_bl,
  ]
        
  ### xiao ble needs a place
  _rp2040_body:
    - what: rectangle
      size: [rp2040_body_width, rp2040_body_height]
      where:
        ref: keyboard_tl
        shift: [-base_width/2+rp2040_body_width/2+m2_outer_distance*2/3, base_height/2-rp2040_body_height/2-1*m2_outer_distance-1.5*m2_head_radius]
  _rp2040_usb:
    - what: rectangle
      size: [8, 9.5]
      where:
        ref: keyboard_tl
        shift: [-base_width/2, base_height/2-rp2040_body_height/2-1*m2_outer_distance-1.5*m2_head_radius]
  _rp2040: [
    _rp2040_body,
    _rp2040_usb
  ]

  ### battery needs a place
  _battery:
    - what: rectangle
      size: [32, 14]
      where:
        ref: matrix_ring_bottom
        shift: [15, -17]
  
  ### symbol 1
  _symbol_circle_bl:
    - what: circle
      radius: symbols_radius
      where:
        shift: [0, 0]
  _symbol_circle_br:
    - what: circle
      radius: symbols_radius
      where:
        shift: [12, 0]
  _symbol_circle_t:
    - what: circle
      radius: symbols_radius
      where:
        shift: [6, 10.3]
  _symbol_triangle:
    - what: polygon
      points:
        - shift: [0,0]
        - shift: [12, 0]
        - shift: [-6, 10.3]

  symbol:
    - what: outline
      name: _symbol_circle_t
    - what: outline
      name: _symbol_circle_bl
      operation: stack
    - what: outline
      name: _symbol_circle_br
      operation: stack
    - what: outline
      name: _symbol_triangle
      operation: subtract

  ### parts that are used on different layers

  ### switch plate
  _thumbs:
    - what: rectangle
      size: [3U, 1U]
      corner: 1
      where:
        ref: thumb_reachy
        shift: [-1U, 0]
  _key_holes:
    - what: rectangle
      where: /^matrix_.*|^thumb_.*/
      size: 14
  _key_frame:
    - what: rectangle
      where: 
        ref: matrix_middle_top
      bound: true
      size: 14
      expand: 8

  _raw_plate:
    - what: outline
      name: _base
    - what: outline
      name: _key_frame
      operation: add
      where:
        shift: [0, 1]
  _with_fillets:
    - what: outline
      name: _raw_plate
      fillet: 4

  ### frame around keycaps on top of switchplate
  _switch_caps:
    - what: polygon # all borders
      operation: stack
      points:
        - ref: matrix_pinky_bottom
          shift: [-10,-10]
        - ref: matrix_pinky_top
          shift: [-10, 10]
        - ref: matrix_pinky_top
          shift: [10, 10]
        - ref: matrix_pinky_home
          shift: [10, 2]
        - ref: matrix_ring_top
          shift: [-10,10]
        - ref: matrix_ring_top
          shift: [9,10]
        - ref: matrix_middle_top
          shift: [-10,10]
        - ref: matrix_middle_top
          shift: [10,10]
        - ref: matrix_index_top
          shift: [-9,10]
        - ref: matrix_index_top
          shift: [10,10]
        - ref: matrix_inner_top
          shift: [-9,10]
        - ref: matrix_inner_top
          shift: [10,10]
        - ref: matrix_inner_bottom
          shift: [10,-6]
        - ref: thumb_reachy
          shift: [15,15]
        - ref: thumb_reachy
          shift: [15,-15]
        - ref: thumb_middle
          shift: [-10,-20]
        - ref: thumb_middle
          shift: [-10, 9]
        - ref: matrix_index_bottom
          shift: [-10,-10]
        - ref: matrix_middle_bottom
          shift: [9,-10]
        - ref: matrix_middle_bottom
          shift: [-9,-10]
        - ref: matrix_ring_bottom
          shift: [10,-10]
        - ref: matrix_ring_bottom
          shift: [-8,-10]
        - ref: matrix_pinky_bottom
          shift: [10,-10]



##########################################
###
###     The actual Layers
###     ordered from bottom to top
###
###     Given conditions:
###     - Each layer is 0.5mm high (thickness of the veneer I bought)
###     - Height of USB-hole: 3mm
###     - Height/width of halves'/mouse connectors holes: 5mm/10mm
###     - M2-Screws and inlets
###     - Kailh choc switches
###     - Keycaps are 17mmx16mm
###     - Keycaps are NOT 18mmx18mm as usual!!
###
###     TODO:
###     - adjust for unusual keycaps size!
###     - height of holes for halves'/mouse connectors
###     - accurate positioning of loose parts between the holes below the switch plate
###
##########################################

  ## bottom plate consists of three layers: 
  ## 01: the voronoi pattern
  ## 02: a blank outline (using a different wood) - maybe with space invaders inlay?
  ## 03: the voronoi pattern again so that keys can be closer to the bottom
  ## Layer 01 has larger holes to accomodate the screw heads, the other layers'
  ##   holes are just large enough to the screws can fit through
  ## 
  ## body below the keyplate: no idea how many layers - let's  make it 6, but 
  ##    maybe some can be skipped 
  ##    Needs to be high enough to house:
  ##    - inlets for screws
  ##    - bottom part of the keys
  ##    - part of battery?
  ##    - most of the microcontroller
  ##    - most of the holes for usb and halves'/mouse connectors
  ## 04-06: several layers with just the hollow but not holes for usb, halves'/mouse connectors
  ## 07-09: several layers with holes for usb and halves'/mouse connectors
  ##
  ## switch plate consists of three layers - goal is a total of 1.5mm for the 
  ##    switch plate, and each layer is around 0.5-0.6mm 
  ##    Might house a part of the holes for usb and halves'/mouse connectors?
  ## 10: switch plate with holes for usb and halves'/mouse connectors
  ## 11: switch plate with holes for usb and halves'/mouse connectors
  ## 13: switch plate without any holes - no idea if that's necessary 
  ##      or if we'll add another layer with holes
  ##
  ## body above the keyplate: no idea how many layers - let's make it another 6,
  ##    with the option so skip some
  ##    Needs to be high enough to 
  ##    - house magnets
  ##    - clear the keycaps: top of keycaps should be almost at top of body
  ##    - topmost layer covers the magnets and holds the decorative inlay

  _key_pattern:
    - what: circle
      # where: false
      where: /^matrix_.*|^thumb_.*/
      radius: 00
  duality_bottom_pattern: [
    _with_fillets,
    +_thumbs,
    -_key_pattern,
    -_screw_heads
  ]


  duality_bottom_bottom: [
    _with_fillets,
    +_thumbs,
    -_screw_holes
  ]


  # switch plate  
  duality: [
    _with_fillets,
    +_thumbs,
    -_key_holes,
    -_rp2040,
    -_battery,
    -_inlet_holes
  ]

  duality_top_frame: [
    _with_fillets,
    -_rp2040,
    -_switch_caps,
    -_magnet_holes,
  ]

  duality_top_frame_without_usb: [
    _with_fillets,
    -_rp2040_body,
    -_switch_caps,
    -_magnet_holes,
  ]
  

  duality_top_cap:
    - what: outline
      name: _with_fillets
    - what: outline
      name: _switch_caps
      operation: subtract
    - what: outline
      name: symbol
      operation: subtract
      origin: symbol


  ### stuff below the the switch plate

  _bottom_hollow:
    - what: rectangle
      size: [base_width-30, base_height-40]
      where:
        ref: keyboard_tl
        shift: [0, 10]
    - what: rectangle
      size: [60, 8]
      where:
        ref: thumb_reachy
        shift: [-35, 3]
    - what: rectangle
      size: [20, 8]
      where:
        ref: matrix_pinky_bottom
        shift: [15, 0]


  duality_bottom_frame: [
    _with_fillets,
    +_thumbs,
    -_key_holes,
    -_bottom_hollow,
    -_rp2040_body,
    -_battery,
    -_inlet_holes
  ]
