units:
  thumb_rotation: -10
  pinky_rotation: 10

points:
  zones:
    matrix:
      columns:
        pinky.rotate: pinky_rotation
        ring.rotate: -pinky_rotation
        ring.stagger: 0.66U
        middle.stagger: 0.25U
        index.stagger: -0.25U
        inner.stagger: -0.15U
      rows:
        bottom.padding: U
        home.padding: U
        top.padding: U
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [-0.3U, -1U]
        rotate: thumb_rotation
      columns:
        tucky:
          key.name: thumb_tucky
        middle:
          key.name: thumb_middle
          origin: [-0.5U, -0.3U]
        reachy:
          key.name: thumb_reachy
          origin: [-0.5U, -0.3U]
  mirror:
    distance: 3U
    ref: thumb_reachy
outlines:
  exports:
    _raw_wood_outline:
      - type: keys
        side: both
        size: [ 12, 12 ]
        corner: -6.5
    _raw_plate:
      - type: keys
        side: both
        size: [ 34, 34 ]
        corner: 2
    _clip_thumb_hole:
      - type: rectangle
        size: [40, 30]
        anchor:
          ref: thumb_tucky
          shift: [-40, -0.89U]
        mirror: true
    _clip_top_stagger:
      - type: rectangle
        size: [116.5, 30]
        corner: 2
        anchor:
          ref: matrix_ring_top
          shift: [-42.5, -8]
        mirror: true
    plate: [
      +_raw_plate,
      +_clip_thumb_hole,
      +_clip_top_stagger
    ]
    _switch_holes:
      - type: keys
        side: both
        size: [ 14,14 ]
    switch_plate:
      - +plate
      - -_switch_holes
    wood: [
      +plate,
      -_raw_wood_outline,
      +_switch_holes
    ]


      